pname_id(taxon_rank, wd:p105).
pname_id(terminologia_embryologica, wd:p1693).
pname_id(nci_thesaurus_id, wd:p1748).
pname_id(terminologia_histologica, wd:p1694).
pname_id(side_effect, wd:p1909).
pname_id(icd9cm, wd:p1692).
pname_id(parent_taxon, wd:p171).
pname_id(regulates_molecular_biology, wd:p128).
pname_id(iucn_conservation_status, wd:p141).
pname_id(natural_reservoir_of, wd:p1606).
pname_id(index_case_of, wd:p1677).
pname_id(icd10pcs, wd:p1690).
pname_id(has_natural_reservoir, wd:p1605).
pname_id(operations_and_procedures_key_ops, wd:p1691).
pname_id(has_index_case, wd:p1660).
pname_id(hgnc_gene_symbol, wd:p353).
pname_id(uniprot_protein_id, wd:p352).
pname_id(entrez_gene_id, wd:p351).
pname_id(molecular_function, wd:p680).
pname_id(pubchem_cid, wd:p662).
pname_id(cell_component, wd:p681).
pname_id(clinvar_variation_id, wd:p1929).
pname_id(violin_id, wd:p1925).
pname_id(health_specialty, wd:p1995).
pname_id(vaccine_ontology_id, wd:p1928).
pname_id(dsm5_classification, wd:p1930).
pname_id(minimal_lethal_concentration, wd:p2710).
pname_id(lymphatic_drainage, wd:p2288).
pname_id(mirtarbase_id, wd:p2646).
pname_id(median_lethal_concentration, wd:p2712).
pname_id(antagonist_muscle, wd:p2329).
pname_id(world_health_organisation_international_nonproprietary_name, wd:p2275).
pname_id(goniat_taxon_id, wd:p5216).
pname_id(the_reptile_database_id, wd:p5473).
pname_id(antweb_id, wd:p5299).
pname_id(floracatalana_id, wd:p5179).
pname_id(czech_ndop_taxon_id, wd:p5263).
pname_id(tierstimmenarchiv_id, wd:p5397).
pname_id(tree_of_life_web_project_id, wd:p5221).
pname_id(invasive_species_compendium_datasheet_id, wd:p5698).
pname_id(global_invasive_species_database_id, wd:p5626).
pname_id(inaturalist_observation_id, wd:p5683).
pname_id(amphibian_species_of_the_world_id, wd:p5354).
pname_id(birdlife_taxon_id, wd:p5257).
pname_id(iucn_taxon_id, wd:p627).
pname_id(ncbi_taxonomy_id, wd:p685).
pname_id(global_biodiversity_information_facility_id, wd:p846).
pname_id(encyclopedia_of_life_id, wd:p830).
pname_id(fossilworks_id, wd:p842).
pname_id(biolib_id, wd:p838).
pname_id(patient_of, wd:p3205).
pname_id(medical_dictionary_for_regulatory_activities_id, wd:p3201).
pname_id(innervated_by, wd:p3189).
pname_id(clinicaltrialsgov_identifier, wd:p3098).
pname_id(innervates, wd:p3190).
pname_id(taxon_range_map_image, wd:p181).
pname_id(fauna_europaea_id, wd:p1895).
pname_id(usda_plants_id, wd:p1772).
pname_id(grassbase_id, wd:p1832).
pname_id(watson__dallwitz_family_id, wd:p1761).
pname_id(dyntaxa_id, wd:p1939).
pname_id(taxonomic_type, wd:p427).
pname_id(lepidoptera_of_belgium_id, wd:p5862).
pname_id(enciclovida_id, wd:p5864).
pname_id(vicflora_id, wd:p5945).
pname_id(nt_flora_id, wd:p5953).
pname_id(apni_id, wd:p5984).
pname_id(center_for_biological_diversity_id, wd:p6003).
pname_id(sealifebase_id, wd:p6018).
pname_id(species_at_risk_public_registry_id, wd:p6019).
pname_id(hymenoptera_online_taxon_id, wd:p6021).
pname_id(oiseauxnet_id, wd:p6025).
pname_id(hypericum_myspecies_id, wd:p6028).
pname_id(ecos_id, wd:p6030).
pname_id(cms_id, wd:p6033).
pname_id(plant_finder_id, wd:p6034).
pname_id(chembl_id, wd:p592).
pname_id(homologene_id, wd:p593).
pname_id(year_of_taxon_name_publication, wd:p574).
pname_id(drug_used_for_treatment, wd:p2176).
pname_id(internetmedicinse_id, wd:p2074).
pname_id(medical_condition_treated, wd:p2175).
pname_id(first_aid_measures, wd:p2239).
pname_id(biological_process, wd:p682).
pname_id(ortholog, wd:p684).
pname_id(encoded_by, wd:p702).
pname_id(posttranslational_modification_association_with, wd:p1917).
pname_id(increased_expression_in, wd:p1911).
pname_id(gene_duplication_association_with, wd:p1913).
pname_id(gene_inversion_association_with, wd:p1915).
pname_id(decreased_expression_in, wd:p1910).
pname_id(gene_insertion_association_with, wd:p1914).
pname_id(deletion_association_with, wd:p1912).
pname_id(vaccine_for, wd:p1924).
pname_id(gene_substitution_association_with, wd:p1916).
pname_id(icd10, wd:p494).
pname_id(diseasesdb, wd:p557).
pname_id(temporal_range_end, wd:p524).
pname_id(species_kept, wd:p1990).
pname_id(altered_regulation_leads_to, wd:p1918).
pname_id(refseq_protein_id, wd:p637).
pname_id(refseq_rna_id, wd:p639).
pname_id(taxonomic_type, wd:p427).
pname_id(wikipathways_id, wd:p2410).
pname_id(unesco_biosphere_reserve_url, wd:p2520).
pname_id(acceptable_daily_intake, wd:p2542).
pname_id(genome_size, wd:p2143).
pname_id(genetic_association, wd:p2293).
pname_id(encyclopedia_of_life_id, wd:p830).
pname_id(fossilworks_id, wd:p842).
pname_id(biolib_id, wd:p838).
pname_id(pdb_ligand_id, wd:p3636).
pname_id(muscle_insertion, wd:p3491).
pname_id(minimal_incubation_period_in_humans, wd:p3488).
pname_id(muscle_origin, wd:p3490).
pname_id(seed_dispersal, wd:p3741).
pname_id(rfam_id, wd:p3523).
pname_id(hgnc_id, wd:p354).
pname_id(significant_drug_interaction, wd:p769).
pname_id(symptoms, wd:p780).
pname_id(hymenium_type, wd:p783).
pname_id(drugbank_id, wd:p715).
pname_id(flora_of_australia_id, wd:p3100).
pname_id(plantarium_id, wd:p3102).
pname_id(florabase_id, wd:p3101).
pname_id(tela_botanica_id, wd:p3105).
pname_id(internet_bird_collection_species_id, wd:p3099).
pname_id(nsw_flora_id, wd:p3130).
pname_id(kegg_id, wd:p665).
pname_id(unii, wd:p652).
pname_id(pubmed_health, wd:p653).
pname_id(dsmiv_classification, wd:p663).
pname_id(connects_with, wd:p2789).
pname_id(age_of_onset, wd:p2841).
pname_id(nsc_number, wd:p2840).
pname_id(noobservedadverseeffect_level, wd:p2717).
pname_id(lowestobservedadverseeffect_level, wd:p2718).
pname_id(biological_process, wd:p682).
pname_id(ortholog, wd:p684).
pname_id(encoded_by, wd:p702).
pname_id(flybase_gene_id, wd:p3852).
pname_id(rat_genome_database_id, wd:p3853).
pname_id(amphibiaweb_species_id, wd:p5036).
pname_id(irmng_id, wd:p5055).
pname_id(amphibians_of_india_id, wd:p5003).
pname_id(plants_of_the_world_online_id, wd:p5037).
pname_id(mgi_gene_symbol, wd:p2394).
pname_id(refseq_genome_id, wd:p2249).
pname_id(ncbi_locus_tag, wd:p2393).
pname_id(virtual_guide_to_the_flora_of_mongolia_id, wd:p6139).
pname_id(verspreidingsatlasnl_id, wd:p6142).
pname_id(atlas_of_florida_plants_id, wd:p6159).
pname_id(invasive_plant_atlas_of_the_united_states_id, wd:p6161).
pname_id(nas_id, wd:p6163).
pname_id(calipc_id, wd:p6176).
pname_id(seinet_id, wd:p6209).
pname_id(flora_of_wisconsin_id, wd:p6227).
pname_id(danmarks_svampeatlas_id, wd:p6268).
pname_id(weeds_in_ontario_id, wd:p6285).
pname_id(odnr_division_of_wildlife_id, wd:p6289).
pname_id(ifpni_species_id, wd:p6341).
pname_id(the_whitefiles_species_id, wd:p6347).
pname_id(lace_bugs_database_id, wd:p6349).
pname_id(psyllist_species_id, wd:p6376).
pname_id(eunis_id_for_species, wd:p6177).
pname_id(bradley_and_fletcher_checklist_number, wd:p1743).
pname_id(flora_of_china_id, wd:p1747).
pname_id(flora_of_north_america_taxon_id, wd:p1727).
pname_id(agassiz_checklist_number, wd:p1744).
pname_id(vascan_id, wd:p1745).
pname_id(zoobank_id_for_name_or_act, wd:p1746).
pname_id(fauna_europaea_id, wd:p1895).
pname_id(usda_plants_id, wd:p1772).
pname_id(grassbase_id, wd:p1832).
pname_id(watson__dallwitz_family_id, wd:p1761).
pname_id(dyntaxa_id, wd:p1939).
pname_id(lepindex_id, wd:p3064).
pname_id(arkive_id, wd:p2833).
pname_id(bacdive_id, wd:p2946).
pname_id(catalogue_of_life_in_taiwan_id, wd:p3088).
pname_id(eppo_code, wd:p3031).
pname_id(butmoth_id, wd:p3060).
pname_id(parent_cell_line, wd:p3432).
pname_id(araneae_spider_id, wd:p3594).
pname_id(autologous_cell_line, wd:p3578).
pname_id(wcspf_id, wd:p3591).
pname_id(euring_number, wd:p3459).
pname_id(calflora_id, wd:p3420).
pname_id(ebird_taxon_id, wd:p3444).
pname_id(bold_systems_taxon_id, wd:p3606).
pname_id(doris_id, wd:p4630).
pname_id(conabio_id, wd:p4902).
pname_id(bto_birds_of_britain_id, wd:p4798).
pname_id(ecocrop_id, wd:p4753).
pname_id(bto_fiveletter_code, wd:p4567).
pname_id(wiki_aves_bird_id, wd:p4664).
pname_id(ubio_id, wd:p4728).
pname_id(mona_id, wd:p4758).
pname_id(phasmida_species_file_id, wd:p4855).
pname_id(guide_to_north_american_birds_id, wd:p4715).
pname_id(isoschizomer, wd:p4873).
pname_id(ictv_virus_genome_composition, wd:p4628).
pname_id(neoschizomer, wd:p4875).
pname_id(pubmed_id, wd:p698).
pname_id(disease_ontology_id, wd:p699).
pname_id(species_kept, wd:p1990).
pname_id(altered_regulation_leads_to, wd:p1918).
pname_id(ictv_virus_id, wd:p1076).
pname_id(algaebase_url, wd:p1348).
pname_id(index_fungorum_id, wd:p1391).
pname_id(grin_url, wd:p1421).
pname_id(hgnc_id, wd:p354).
pname_id(gestation_period, wd:p3063).
pname_id(saccharomyces_genome_database_id, wd:p3406).
pname_id(biological_variant_of, wd:p3433).
pname_id(significant_drug_interaction, wd:p769).
pname_id(symptoms, wd:p780).
pname_id(hymenium_type, wd:p783).
pname_id(drugbank_id, wd:p715).
pname_id(minimal_lethal_concentration, wd:p2710).
pname_id(lymphatic_drainage, wd:p2288).
pname_id(mirtarbase_id, wd:p2646).
pname_id(median_lethal_concentration, wd:p2712).
pname_id(antagonist_muscle, wd:p2329).
pname_id(world_health_organisation_international_nonproprietary_name, wd:p2275).
pname_id(flybase_gene_id, wd:p3852).
pname_id(rat_genome_database_id, wd:p3853).
pname_id(amphibiaweb_species_id, wd:p5036).
pname_id(irmng_id, wd:p5055).
pname_id(amphibians_of_india_id, wd:p5003).
pname_id(plants_of_the_world_online_id, wd:p5037).
pname_id(mgi_gene_symbol, wd:p2394).
pname_id(refseq_genome_id, wd:p2249).
pname_id(ncbi_locus_tag, wd:p2393).
pname_id(wikipathways_id, wd:p2410).
pname_id(unesco_biosphere_reserve_url, wd:p2520).
pname_id(acceptable_daily_intake, wd:p2542).
pname_id(genome_size, wd:p2143).
pname_id(genetic_association, wd:p2293).
pname_id(cell_line_ontology_id, wd:p2158).
pname_id(conifersorg_id, wd:p1940).
pname_id(cites_species_id, wd:p2040).
pname_id(hgnc_gene_symbol, wd:p353).
pname_id(uniprot_protein_id, wd:p352).
pname_id(plazi_id, wd:p1992).
pname_id(lpsn_url, wd:p1991).
pname_id(african_plant_database_id, wd:p2036).
pname_id(avibase_id, wd:p2026).
pname_id(german_cattle_breed_id, wd:p2024).
pname_id(world_spider_catalog_id, wd:p3288).
pname_id(vlinderstichtingid, wd:p3322).
pname_id(taxref_id, wd:p3186).
pname_id(inaturalist_taxon_id, wd:p3151).
pname_id(nbn_system_key, wd:p3240).
pname_id(fao_2007_genetic_resource_id, wd:p3380).
pname_id(nederlands_soortenregister_id, wd:p3405).
pname_id(cellosaurus_id, wd:p3289).
pname_id(butterflies_and_moths_of_north_america_id, wd:p3398).
pname_id(fauna_europaea_id, wd:p1895).
pname_id(usda_plants_id, wd:p1772).
pname_id(grassbase_id, wd:p1832).
pname_id(watson__dallwitz_family_id, wd:p1761).
pname_id(dyntaxa_id, wd:p1939).
pname_id(prevalence, wd:p1193).
pname_id(mode_of_inheritance, wd:p1199).
pname_id(pathogen_transmission_process, wd:p1060).
pname_id(medical_treatment, wd:p924).
pname_id(edibility, wd:p789).
pname_id(medical_examinations, wd:p923).
pname_id(australasian_pollen_and_spore_atlas_code, wd:p2809).
pname_id(flower_color, wd:p2827).
pname_id(lepindex_id, wd:p3064).
pname_id(eppo_code, wd:p3031).
pname_id(butmoth_id, wd:p3060).
pname_id(arkive_id, wd:p2833).
pname_id(bacdive_id, wd:p2946).
pname_id(catalogue_of_life_in_taiwan_id, wd:p3088).
pname_id(chromosome, wd:p1057).
pname_id(bradley_and_fletcher_checklist_number, wd:p1743).
pname_id(flora_of_china_id, wd:p1747).
pname_id(new_zealand_organisms_register_id, wd:p2752).
pname_id(parent_cell_line, wd:p3432).
pname_id(araneae_spider_id, wd:p3594).
pname_id(doris_id, wd:p4630).
pname_id(conabio_id, wd:p4902).
pname_id(venous_drainage, wd:p2289).
pname_id(autologous_cell_line, wd:p3578).
pname_id(wcspf_id, wd:p3591).
pname_id(bto_birds_of_britain_id, wd:p4798).
pname_id(mouse_genome_informatics_id, wd:p671).
pname_id(foundational_model_of_anatomy_id, wd:p1402).
pname_id(flora_of_north_america_taxon_id, wd:p1727).
pname_id(species_profile_and_threats_database_id, wd:p2455).
pname_id(euring_number, wd:p3459).
pname_id(ecocrop_id, wd:p4753).
pname_id(fossil_found_in_this_unit, wd:p1137).
pname_id(uberon_id, wd:p1554).
pname_id(index_hepaticarum_id, wd:p2794).
pname_id(bto_fiveletter_code, wd:p4567).
pname_id(wiki_aves_bird_id, wd:p4664).
pname_id(emedicine, wd:p673).
pname_id(encodes, wd:p688).
pname_id(parent_cell_line, wd:p3432).
pname_id(araneae_spider_id, wd:p3594).
pname_id(autologous_cell_line, wd:p3578).
pname_id(wcspf_id, wd:p3591).
pname_id(euring_number, wd:p3459).
pname_id(calflora_id, wd:p3420).
pname_id(ebird_taxon_id, wd:p3444).
pname_id(bold_systems_taxon_id, wd:p3606).
pname_id(ensembl_transcript_id, wd:p704).
pname_id(found_in_taxon, wd:p703).
pname_id(virtual_guide_to_the_flora_of_mongolia_id, wd:p6139).
pname_id(verspreidingsatlasnl_id, wd:p6142).
pname_id(atlas_of_florida_plants_id, wd:p6159).
pname_id(invasive_plant_atlas_of_the_united_states_id, wd:p6161).
pname_id(nas_id, wd:p6163).
pname_id(calipc_id, wd:p6176).
pname_id(seinet_id, wd:p6209).
pname_id(flora_of_wisconsin_id, wd:p6227).
pname_id(danmarks_svampeatlas_id, wd:p6268).
pname_id(weeds_in_ontario_id, wd:p6285).
pname_id(odnr_division_of_wildlife_id, wd:p6289).
pname_id(ifpni_species_id, wd:p6341).
pname_id(the_whitefiles_species_id, wd:p6347).
pname_id(lace_bugs_database_id, wd:p6349).
pname_id(psyllist_species_id, wd:p6376).
pname_id(eunis_id_for_species, wd:p6177).
pname_id(biological_phase, wd:p4774).
pname_id(cutting_site_of_restriction_enzyme, wd:p4864).
pname_id(recognition_sequence, wd:p4863).
pname_id(rebase_enzyme_number, wd:p4866).
pname_id(isoschizomer, wd:p4873).
pname_id(ictv_virus_genome_composition, wd:p4628).
pname_id(neoschizomer, wd:p4875).
pname_id(lepindex_id, wd:p3064).
pname_id(arkive_id, wd:p2833).
pname_id(bacdive_id, wd:p2946).
pname_id(catalogue_of_life_in_taiwan_id, wd:p3088).
pname_id(eppo_code, wd:p3031).
pname_id(butmoth_id, wd:p3060).
pname_id(flora_of_australia_id, wd:p3100).
pname_id(vlinderstichtingid, wd:p3322).
pname_id(plantarium_id, wd:p3102).
pname_id(florabase_id, wd:p3101).
pname_id(tela_botanica_id, wd:p3105).
pname_id(nsw_flora_id, wd:p3130).
pname_id(butterflies_and_moths_of_north_america_id, wd:p3398).
pname_id(internet_bird_collection_species_id, wd:p3099).
pname_id(wikipathways_id, wd:p2410).
pname_id(unesco_biosphere_reserve_url, wd:p2520).
pname_id(acceptable_daily_intake, wd:p2542).
pname_id(genome_size, wd:p2143).
pname_id(genetic_association, wd:p2293).
pname_id(cnps_id, wd:p4194).
pname_id(paldat_plant_id, wd:p4122).
pname_id(has_fruit_type, wd:p4000).
pname_id(titan_id, wd:p4125).
pname_id(uk_national_fruit_collection_id, wd:p4288).
pname_id(xenopus_anatomical_ontology_id, wd:p4495).
pname_id(indian_foundation_for_butterflies_id, wd:p4433).
pname_id(pfaf_id, wd:p4301).
pname_id(aba_bird_id, wd:p4526).
pname_id(code_of_nomenclature, wd:p944).
pname_id(postsynaptic_connection, wd:p926).
pname_id(anatomical_location, wd:p927).
pname_id(presynaptic_connection, wd:p925).
pname_id(flower_color, wd:p2827).
pname_id(biorxiv_id, wd:p3951).
pname_id(prosite_documentation_id, wd:p4355).
pname_id(bhl_creator_id, wd:p4081).
pname_id(cytogenetic_location, wd:p4196).
pname_id(genbank_assembly_accession, wd:p4333).
pname_id(reactome_id, wd:p3937).
pname_id(evidence__conclusion_ontology_id, wd:p3811).
pname_id(zfin_gene_id, wd:p3870).
pname_id(half_maximal_inhibitory_concentration_ic50, wd:p4268).
pname_id(ex_taxon_author, wd:p697).
pname_id(replaced_synonym_for_nom_nov, wd:p694).
pname_id(neurolex_id, wd:p696).
pname_id(author_citation_zoology, wd:p835).
pname_id(birdlife_international_iba_id, wd:p6070).
pname_id(mushroom_cap_shape, wd:p784).
pname_id(mushroom_ecological_type, wd:p788).
pname_id(spore_print_color, wd:p787).
pname_id(hymenium_attachment, wd:p785).
pname_id(stipe_character, wd:p786).
pname_id(evaluation_of, wd:p5134).
pname_id(chromosome_count, wd:p5230).
pname_id(bmrb_id, wd:p5219).
pname_id(goniat_paper_id, wd:p5214).
pname_id(medical_evacuation_to, wd:p5248).
pname_id(biu_sant_person_id, wd:p5375).
pname_id(armb_member_id, wd:p5329).
pname_id(goniat_place_id, wd:p5215).
pname_id(goniat_author_id, wd:p5211).
pname_id(mondo_id, wd:p5270).
pname_id(adw_taxon_id, wd:p4024).
pname_id(heart_rate, wd:p3395).
pname_id(bite_force_quotient, wd:p3485).
pname_id(mirbase_mature_mirna_id, wd:p2871).
pname_id(mirbase_premirna_id, wd:p2870).
pname_id(ucsc_genome_browser_assembly_id, wd:p2576).
pname_id(pubchem_bioassay_id_aid, wd:p2874).
pname_id(biostor_work_id, wd:p5315).
pname_id(pasteur_institute_person_id, wd:p5418).
pname_id(bioone_journal_id, wd:p6143).
pname_id(foundational_model_of_anatomy_id, wd:p1402).
pname_id(fossil_found_in_this_unit, wd:p1137).
pname_id(uberon_id, wd:p1554).
pname_id(is_pollinated_by, wd:p1703).
pname_id(inflorescence, wd:p3739).
pname_id(simple_modular_architecture_research_tool_id, wd:p3524).
pname_id(afflicts, wd:p689).
pname_id(emedicine, wd:p673).
pname_id(encodes, wd:p688).
pname_id(venous_drainage, wd:p2289).
pname_id(arterial_supply, wd:p2286).
pname_id(entomologists_of_the_world_id, wd:p5370).
pname_id(brenda_tissue_ontology_id, wd:p5501).
pname_id(history_of_modern_biomedicine_id, wd:p3885).
pname_id(legal_status_medicine, wd:p3493).
pname_id(basic_reproduction_number, wd:p3492).
pname_id(national_drug_code, wd:p3640).
pname_id(australian_register_of_therapeutic_goods_id, wd:p3550).
pname_id(european_medicines_agency_product_number, wd:p3637).
pname_id(gpnotebook_id, wd:p3720).
pname_id(human_phenotype_ontology_id, wd:p3841).
pname_id(ranm_member_id, wd:p3945).
pname_id(icd10, wd:p494).
pname_id(diseasesdb, wd:p557).
pname_id(temporal_range_end, wd:p524).
pname_id(medical_condition, wd:p1050).
pname_id(neurological_function, wd:p970).
pname_id(ensembl_transcript_id, wd:p704).
pname_id(found_in_taxon, wd:p703).
pname_id(number_of_cases, wd:p1603).
pname_id(biosafety_level, wd:p1604).
pname_id(malacards_id, wd:p1583).
pname_id(orphanet_id, wd:p1550).
pname_id(animal_breed, wd:p4743).
pname_id(harvard_botanical_journal_id, wd:p4754).
pname_id(spider_ontology_id, wd:p4537).
pname_id(chromosome_numbers_of_the_flora_of_germany_database_id, wd:p5231).
pname_id(invasive_to, wd:p5588).
pname_id(bgci_garden_id, wd:p5818).
pname_id(index_herbariorum_code, wd:p5858).
pname_id(taxonomic_literature_2_number, wd:p5878).
pname_id(pubmed_id, wd:p698).
pname_id(disease_ontology_id, wd:p699).
pname_id(significant_drug_interaction, wd:p769).
pname_id(symptoms, wd:p780).
pname_id(hymenium_type, wd:p783).
pname_id(drugbank_id, wd:p715).
pname_id(ex_taxon_author, wd:p697).
pname_id(replaced_synonym_for_nom_nov, wd:p694).
pname_id(neurolex_id, wd:p696).
pname_id(zoobank_publication_id, wd:p2007).
pname_id(gait, wd:p2839).
pname_id(this_zoological_name_is_coordinate_with, wd:p2743).
pname_id(minimum_frequency_of_audible_sound, wd:p3387).
pname_id(heart_rate, wd:p3395).
pname_id(bite_force_quotient, wd:p3485).
pname_id(maximum_frequency_of_audible_sound, wd:p3465).
pname_id(wormbase_gene_id, wd:p3860).
pname_id(normal_respiratory_rate, wd:p3486).
pname_id(route_of_administration, wd:p636).
pname_id(refseq_rna_id, wd:p639).
pname_id(mushroom_cap_shape, wd:p784).
pname_id(mushroom_ecological_type, wd:p788).
pname_id(spore_print_color, wd:p787).
pname_id(hymenium_attachment, wd:p785).
pname_id(stipe_character, wd:p786).
pname_id(taxon_common_name, wd:p1843).
pname_id(this_taxon_is_source_of, wd:p1672).
pname_id(original_combination, wd:p1403).
pname_id(zoobank_author_id, wd:p2006).
pname_id(habitat, wd:p2974).
pname_id(life_expectancy, wd:p2250).
pname_id(gender_of_a_scientific_name_of_a_genus, wd:p2433).
pname_id(taxon_synonym, wd:p1420).
pname_id(ecoregion_wwf, wd:p1425).
pname_id(patientplus_id, wd:p1461).
pname_id(harvard_index_of_botanists_id, wd:p6264).
pname_id(plant_illustrations_artist_id, wd:p6605).
pname_id(index_to_american_botanical_literature_id, wd:p6626).
pname_id(worms_source_id, wd:p6678).
pname_id(code_of_nomenclature, wd:p944).
pname_id(postsynaptic_connection, wd:p926).
pname_id(anatomical_location, wd:p927).
pname_id(presynaptic_connection, wd:p925).
pname_id(author_citation_zoology, wd:p835).
pname_id(birdlife_international_iba_id, wd:p6070).
pname_id(medical_treatment, wd:p924).
pname_id(edibility, wd:p789).
pname_id(medical_examinations, wd:p923).
pname_id(prevalence, wd:p1193).
pname_id(mode_of_inheritance, wd:p1199).
pname_id(pathogen_transmission_process, wd:p1060).
pname_id(host, wd:p2975).
pname_id(taxonomic_literature_2_number, wd:p5878).
pname_id(entomologists_of_the_world_id, wd:p5370).
pname_id(brenda_tissue_ontology_id, wd:p5501).
pname_id(host, wd:p2975).
pname_id(natureserve_conservation_status, wd:p3648).
pname_id(generation_time, wd:p3337).
pname_id(highest_observed_lifespan, wd:p4214).
pname_id(means_of_locomotion, wd:p3512).
pname_id(type_locality_biology, wd:p5304).
pname_id(publication_in_which_this_taxon_name_was_established, wd:p5326).
pname_id(status_in_the_red_list_of_threatened_species_in_the_czech_republic, wd:p5841).
pname_id(pombase_systematic_id, wd:p6245).
pname_id(taxon_author_citation, wd:p6507).
